name: CI

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - name: Run Biome
        run: biome ci ./src
      - name: Run Tests
        run: pnpm test